"""The dependency audit, checked from a machine that must not use the network.

``tools/audit_dependencies.py`` exists to ask PyPI and OSV a question, and
the suite may not ask anyone anything — see ``tests/test_security.py``, which
fails if any of this project's own code so much as imports a way to. So what
is checked here is everything around the call: reading the lock, working out
which packages came back and which did not, and finding the external
binaries.

That division is not a compromise. The part of this tool that could be wrong
without anybody noticing is the bookkeeping, not the query: ``pip-audit``
answering "no known vulnerabilities" about half the lock while the report
says the lock is clean is the failure worth a test, and it is entirely
offline to reproduce.
"""

from __future__ import annotations

from pathlib import Path

import audit_dependencies as audit
import pytest

EXPORTED = """\
# This file was autogenerated by uv via the following command:
#    uv export --no-dev --all-extras --format requirements-txt
numpy==2.5.3
    # via
    #   comictrans
    #   opencv-python-headless
pillow==12.3.0
    # via comictrans
pyobjc-core==12.2.2 ; sys_platform == 'darwin'
    # via pyobjc-framework-vision
ruamel-yaml==0.19.1
    # via comictrans
"""
"""A real export, trimmed. Kept verbatim in shape — the leading comment, the
indented ``# via`` blocks, the marker on its own requirement — because those
are exactly what the parser has to get right."""


def test_the_lock_is_read_as_requirements_and_not_as_their_annotations() -> None:
    """A ``# via`` line names a package and is not one.

    ``comictrans`` and ``opencv-python-headless`` appear under numpy as the
    things that pulled it in. A parser that took every name it saw would
    audit them as packages in their own right and report the project against
    itself — and ``comictrans`` is not on PyPI, so what that produces is not
    a wrong answer but a failed run.
    """
    packages = audit.locked_packages(EXPORTED)

    assert [package.name for package in packages] == [
        "numpy",
        "pillow",
        "pyobjc-core",
        "ruamel-yaml",
    ]
    assert packages[0].version == "2.5.3"


def test_an_environment_marker_is_not_part_of_the_version() -> None:
    """``pyobjc-core==12.2.2 ; sys_platform == 'darwin'`` is one version."""
    versions = {p.name: p.version for p in audit.locked_packages(EXPORTED)}

    assert versions["pyobjc-core"] == "12.2.2", "the marker came through as part of it"


def test_an_empty_export_is_no_packages_rather_than_an_error() -> None:
    assert audit.locked_packages("") == ()


@pytest.mark.parametrize(
    ("lock_name", "audit_name"),
    [("ruamel.yaml", "ruamel-yaml"), ("ruamel_yaml", "ruamel-yaml"), ("Pillow", "pillow")],
)
def test_a_package_is_the_same_package_however_it_is_spelled(
    lock_name: str, audit_name: str
) -> None:
    """The two lists being compared come from two tools that spell differently.

    Without this the report would name ``ruamel.yaml`` as unaudited on every
    run, which is a false alarm that teaches people to ignore the section it
    appears in.
    """
    assert audit._normalised(lock_name) == audit._normalised(audit_name)


def test_a_package_the_audit_skipped_is_reported_rather_than_counted_as_clean(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """The failure this tool exists to prevent.

    ``pip-audit`` asked the ordinary way drops a requirement whose marker
    excludes the machine, and one already present in the environment it
    builds, and says nothing about either. Measured on this lock before it
    was asked differently: five ``pyobjc`` packages missing on Linux, and
    ``packaging`` missing on both platforms because ``pip-audit`` depends on
    ``packaging`` itself. A run that reported "no known vulnerabilities" and
    stopped there would have been describing two thirds of the lock in the
    words of the whole of it.

    ``--disable-pip`` and stripped markers close both, so the count reads
    18 of 18 now. This stays because the count is what *told* anyone: the
    guard is worth more than the gap it found, and a future pip-audit can
    start dropping something else.
    """
    monkeypatch.setattr(audit, "export_lock", lambda: EXPORTED)
    monkeypatch.setattr(
        audit,
        "_pip_audit",
        lambda _requirements: [
            {"name": "numpy", "version": "2.5.3", "vulns": []},
            {"name": "ruamel-yaml", "version": "0.19.1", "vulns": []},
        ],
    )
    monkeypatch.setattr(audit, "external_tools", tuple)

    report = audit.audit(tmp_path)

    assert not report.findings
    assert report.audited == ("numpy", "ruamel-yaml")
    assert [package.name for package in report.unaudited] == ["pillow", "pyobjc-core"]


def test_an_advisory_is_read_out_with_the_version_that_fixes_it(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """What a finding has to carry to be worth waking up to.

    The identifier alone is a thing to go and look up; the identifier with a
    fixed version is a thing to go and do. A vulnerability with no fix yet is
    a real state and is kept distinct from one whose fix was not read.
    """
    monkeypatch.setattr(audit, "export_lock", lambda: EXPORTED)
    monkeypatch.setattr(
        audit,
        "_pip_audit",
        lambda _requirements: [
            {
                "name": "pillow",
                "version": "12.3.0",
                "vulns": [
                    {"id": "GHSA-fake-0001", "fix_versions": ["12.3.1", "13.0.0"]},
                    {"id": "GHSA-fake-0002", "fix_versions": []},
                ],
            }
        ],
    )
    monkeypatch.setattr(audit, "external_tools", tuple)

    report = audit.audit(tmp_path)

    assert [finding.identifier for finding in report.findings] == [
        "GHSA-fake-0001",
        "GHSA-fake-0002",
    ]
    assert report.findings[0].fixed_in == ("12.3.1", "13.0.0")
    assert report.findings[1].fixed_in == (), "no fix is not the same as a fix nobody read"


def test_a_binary_that_is_not_installed_is_said_to_be_missing(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Absent is an answer, and a different one from absent-and-unmentioned.

    CBR input needs a RAR tool this project will not ship, so a machine
    without one is ordinary rather than broken. What the report must not do
    is leave the line out, which reads as "audited, fine".
    """
    monkeypatch.setattr(audit.shutil, "which", lambda _name: None)
    monkeypatch.delenv("COMICTRANS_UNRAR", raising=False)
    monkeypatch.delenv("COMICTRANS_RAR", raising=False)

    tools = {tool.name: tool for tool in audit.external_tools()}

    assert set(tools) == {"unrar", "rar", "tesseract"}
    assert all(not tool.path for tool in tools.values())
    assert all(not tool.version for tool in tools.values())


def test_the_variable_that_names_a_tool_elsewhere_names_it_here_too(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """``COMICTRANS_RAR`` is what ``pack.rar_compressor`` reads first.

    An audit that reported the ``rar`` on ``PATH`` while the application ran
    the one in Preferences would be reporting the wrong binary, which is
    worse than reporting none — see ``external_tools``.
    """
    elsewhere = tmp_path / "rar"
    elsewhere.write_text("#!/bin/sh\necho 'RAR 9.99 pretend build'\n", encoding="utf-8")
    elsewhere.chmod(0o755)
    monkeypatch.setenv("COMICTRANS_RAR", str(elsewhere))
    monkeypatch.setattr(audit.shutil, "which", lambda _name: "/usr/bin/rar")

    found = {tool.name: tool for tool in audit.external_tools()}["rar"]

    assert found.path == str(elsewhere), "PATH won over the variable"
    assert found.named_by == "COMICTRANS_RAR"
    assert found.version == "RAR 9.99 pretend build"


def test_a_binary_that_cannot_be_run_is_reported_rather_than_raised(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """A version check is not worth failing an audit over.

    The interesting half of the report is the advisories; a ``rar`` that is
    there and will not start should say so on its own line and let the rest
    of the run finish.
    """
    broken = tmp_path / "unrar"
    broken.write_text("not a program", encoding="utf-8")
    broken.chmod(0o644)  # there, and not executable
    monkeypatch.setenv("COMICTRANS_UNRAR", str(broken))
    monkeypatch.setattr(audit.shutil, "which", lambda _name: None)

    found = {tool.name: tool for tool in audit.external_tools()}["unrar"]

    assert found.path == str(broken)
    assert "could not be run" in found.version


# -- the exit code, which is the whole of what a scheduled run reads ----------


def _report(**overrides: object) -> audit.Report:
    return audit.Report(**overrides)  # type: ignore[arg-type]


@pytest.mark.parametrize(
    ("report", "expected", "why"),
    [
        (_report(), 0, "nothing found and nothing missed"),
        (
            _report(findings=(audit.Finding("pillow", "12.3.0", "GHSA-x", ()),)),
            1,
            "an advisory",
        ),
        (_report(unaudited=(audit.Package("pyobjc-core", "12.2.2"),)), 1, "a package skipped"),
    ],
)
def test_the_run_answers_non_zero_for_anything_worth_looking_at(
    report: audit.Report,
    expected: int,
    why: str,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Run on a schedule, this exit code is the entire message.

    A finding is the obvious one. A package that could not be audited is the
    one worth spelling out: a job that went green while the platform it runs
    on had quietly stopped covering a third of the lock would be worse than
    no job, because it would be evidence of something that was never checked.
    """
    monkeypatch.setattr(audit, "_importable", lambda _module: True)
    monkeypatch.setattr(audit, "audit", lambda _workspace: report)

    assert audit.main() == expected, why
    assert capsys.readouterr().out, "it went quiet as well as green"


def test_without_pip_audit_it_says_how_to_get_it_rather_than_failing_obscurely(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The likeliest way to meet this tool is by running it the wrong way.

    It is not a dependency of anything — installing comictrans must not pull
    an auditor, the same rule that keeps the bundler out of ``dev`` — so the
    ordinary first run is one without it, and what that prints is the whole
    of the documentation most people will read.
    """
    monkeypatch.setattr(audit, "_importable", lambda _module: False)

    with pytest.raises(SystemExit) as raised:
        audit.main()

    assert "uv run --with pip-audit" in str(raised.value)


# -- the two things that make the count 18 of 18 ------------------------------


def test_what_pip_audit_is_handed_carries_no_markers() -> None:
    """A marker is a question about the machine, and this is not installing.

    Left on, what gets audited depends on where the audit ran: no pyobjc on
    Linux, and nothing marked the other way on a Mac. Measured — the same
    lock came back 12 of 18 on Linux with them, and 18 of 18 without.
    """
    written = audit.requirements_for(audit.locked_packages(EXPORTED))

    assert written.splitlines() == [
        "numpy==2.5.3",
        "pillow==12.3.0",
        "pyobjc-core==12.2.2",
        "ruamel-yaml==0.19.1",
    ]
    assert ";" not in written and "sys_platform" not in written


def test_the_resolver_is_turned_off_and_that_is_not_an_optimisation(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """``--disable-pip`` is what makes stripping the markers safe.

    With the resolver on, a requirements file with no markers is one pip
    tries to *build* pyobjc from off a Mac — "PyObjC requires macOS to
    build" — which fails the whole run rather than skipping one package. The
    two go together, and the one that is a bare flag in an argument list is
    the one somebody removes while tidying.

    It is also what stops ``pip-audit`` losing a package that is already in
    the environment it builds, which is how ``packaging`` went unaudited on
    every platform: ``pip-audit`` depends on ``packaging``.
    """
    seen: list[list[str]] = []

    class _Done:
        returncode = 0
        stdout = '{"dependencies": []}'
        stderr = ""

    def _record(command: list[str], **_kwargs: object) -> _Done:
        seen.append(command)
        return _Done()

    monkeypatch.setattr(audit.subprocess, "run", _record)

    audit._pip_audit(tmp_path / "requirements.txt")

    assert seen, "pip-audit was never run"
    assert "--disable-pip" in seen[0], "the resolver is back on; the markers must go back too"
    assert "--no-deps" in seen[0]
    assert seen[0][0] == audit.sys.executable, "some other interpreter is answering"


def test_the_file_pip_audit_is_pointed_at_is_the_built_one(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """``requirements_for`` being right is no use if nothing calls it.

    ``export_lock`` hands back what ``uv`` wrote, markers included, and
    writing *that* to the file is a one-word slip that reads perfectly well
    and quietly restores the platform gap.
    """
    handed: list[str] = []
    monkeypatch.setattr(audit, "export_lock", lambda: EXPORTED)
    monkeypatch.setattr(
        audit,
        "_pip_audit",
        lambda requirements: handed.append(requirements.read_text(encoding="utf-8")) or [],
    )
    monkeypatch.setattr(audit, "external_tools", tuple)

    audit.audit(tmp_path)

    assert handed, "pip-audit was never pointed at anything"
    assert "sys_platform" not in handed[0], "the raw export went through, markers and all"
    assert "# via" not in handed[0]
    assert handed[0].splitlines()[0] == "numpy==2.5.3"
